GH-426: Modify projects pages (resolves #426)
inclusive-design/idrc pull request #480
Opened 2023-02-01 19:42 UTC by cindyli

* [X] This pull request has been tested by running `npm run test` without errors
* [X] This pull request has been built by running `npm run build` without errors
* [X] This isn't a duplicate of an existing pull request

## Description

This pull request implements:
1. The new landing page for the "Projects" page;
2. Allow each project to have sub-pages.

## Steps to test

1. Open the deploy preview and go to "Projects";
2. The landing page should match the new design;
3. Open the admin page to author multiple pages for a project. Subpages should select "parent page title";
4. Go back to the "Projects" page and select this project. The hierarchy of pages should present in the way that's described in the https://github.com/inclusive-design/idrc/issues/426.

**Expected behavior:** 
Described above.

2023-02-01 21:01 UTC, jhung commented
I was testing and have some questions and found some issues:

Issues:
- Project listing description is mandatory, but should be optional if a parent page is specified. Otherwise user will get an error when trying to submit a new sub page and may input garbage data to avoid the error which may lead to confusion down the road.
- Project body is mandatory, but should be optional if there is a project listing description for situations for projects with no internal page (and just a link to an external website).
- Sub page ordering does not appear to work despite specifying a value.

Improvements:
- Add help text to the Title field: "Suggestion: use a descriptive title which includes keywords from the project."
- Change "Short Name" to "Project Short Name"
- Add help text to Short Name field: "Short name for the project. This is used to generate the name for external project website links."
- Add help text to the Project Name field: "Suggestion: If this is a subpage of a project, enter the name of the project here."

2023-02-01 21:21 UTC, cindyli commented
Thanks for great suggestions, @jhung. The last commit should address them all.

Regarding "Sub page ordering does not appear to work despite specifying a value", I cannot reproduce the problem. The child pages are listed on the side navigation menu in the ascending order of "subpage order" value - the lowest order number will show at the top while the highest at the bottom.

Can you describe steps to reproduce the problem? We can have a call if it makes easier.

2023-02-15 15:29 UTC, cindyli commented
@jhung, as we discussed, I removed the `tags` field from the project config and the template. This pull request is ready for a review. Thanks.

2023-02-28 22:55 UTC, jhung requested changes
I made some suggested changes for the content editor labels and hint text.

No other issues found.

2023-02-28 22:55 UTC, jhung commented on src/admin/config.yml
> +      - {label: "Subpage Order", name: "subPageOrder", widget: "number", required: false, hint: "Only select for sub-page of a project."}
```suggestion
      - {label: "Subpage Order", name: "subPageOrder", widget: "number", required: false, hint: "Hint: if using this, all sub-pages at the same level should have an order number specified. Leave blank to have sub-pages appear in alphabetical order. "}
```

2023-02-28 22:55 UTC, jhung commented on src/admin/config.yml
> +      - {label: "Thumbnail Image", name: "thumbnailImage", widget: "image", required: false}
```suggestion
      - {label: "Thumbnail Image", name: "thumbnailImage", widget: "image", required: false, hint: "Suggested size: 680x494px. Images not fitting this aspect ratio will appear stretched."}
```

2023-02-28 22:55 UTC, jhung commented on src/admin/config.yml
> +      - {label: "Project Listing Description", name: "description", widget: "markdown", required: false, editor_components: ["image"], hint: "Only write this description for the main page of a projec
```suggestion
      - {label: "Project Listing Description", name: "description", widget: "markdown", required: false, editor_components: ["image"], hint: "This is text that appears for a project in the projects listing. This description is not required for sub-pages."}
```

2023-02-28 22:55 UTC, jhung commented on src/admin/config.yml
> +      - {label: "External Project Website", name: "link", widget: "string", required: false}
```suggestion
      - {label: "External Project Website", name: "link", widget: "string", required: false, hint: "This is not required for sub-pages."}
```

2023-02-28 22:55 UTC, jhung commented on src/admin/config.yml
> +      - {label: "Body", name: "body", required: false, widget: "markdown"}
```suggestion
      - {label: "Body", name: "body", required: false, widget: "markdown", hint: "This is the content that appears for a project page hosted on the IDRC site."}
```

2023-02-28 22:55 UTC, jhung commented on src/admin/config.yml
> +      - {label: "Project Name", name: "projectName", widget: "string", required: true, hint: "Suggestion: If this is a subpage of a project, enter the name of the project here."}
```suggestion
      - {label: "Project Name", name: "projectName", widget: "string", required: true, hint: "Suggestion: If this is a sub-page of a project, enter the name of the project here."}
```

2023-02-28 22:55 UTC, jhung commented on src/admin/config.yml
> +      - {label: "Title", name: "title", widget: "string", required: true, hint: "Suggestion: use a descriptive title which includes keywords from the project."}
```suggestion
      - {label: "Body Title", name: "title", widget: "string", required: true, hint: "The title that appears after the Project Name and before the Body content. Suggestion: use a descriptive title which includes keywords from the project."}
```

2023-03-01 16:14 UTC, jhung approved these changes

2023-03-01 16:37 UTC, merged